In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import nltk
from nltk.corpus import stopwords
import re
from string import punctuation

In [2]:
df = pd.read_csv("bitcoin.csv", encoding = 'cp1252')
df.head()

,Unnamed: 0,Author,Text,Retweet_Count,Timestamp
0,0,ewin74698177,RT @SolarisCoin: Take a peek @ https://t.co/W8...,49,2018-10-27 23:25:41
1,1,thegustians,RT @SolarisCoin: Take a peek @ https://t.co/W8...,49,2018-10-27 23:10:20
2,2,frg_x,RT @SolarisCoin: Take a peek @ https://t.co/W8...,49,2018-10-27 23:07:04
3,3,TechniCraftCZ,RT @CryptoPepes: CryptoPepes just soft launche...,93,2018-10-27 23:02:48
4,4,victordorofeev1,RT @SolarisCoin: Take a peek @ https://t.co/W8...,49,2018-10-27 23:01:47

In [3]:
df.tail()

,Unnamed: 0,Author,Text,Retweet_Count,Timestamp
1353,1353,mkorkmazbtc,BOUGHT [ #BTCUSDT | #binance | Price: 6522.610...,0,2018-10-20 00:36:41
1354,1354,Bot_Krypto,BOUGHT [ #BTCUSDT | #binance | Price: 6522.610...,0,2018-10-20 00:36:41
1355,1355,Nateist_,RT @GreenblockCoin: Get a chance to win 1000.0...,43,2018-10-20 00:04:43
1356,1356,TradeStrategyCo,Real-time #bitcoin price + news analysis of 15...,0,2018-10-20 00:00:56
1357,1357,BSD_Masternode,#cryptocurrency Price Analysis for #Bitsend #B...,0,2018-10-20 00:00:07

In [7]:
df = df.rename(columns = {'Text' : 'description'})
df.head()

,Unnamed: 0,Author,description,Retweet_Count,Timestamp
0,0,ewin74698177,RT @SolarisCoin: Take a peek @ https://t.co/W8...,49,2018-10-27 23:25:41
1,1,thegustians,RT @SolarisCoin: Take a peek @ https://t.co/W8...,49,2018-10-27 23:10:20
2,2,frg_x,RT @SolarisCoin: Take a peek @ https://t.co/W8...,49,2018-10-27 23:07:04
3,3,TechniCraftCZ,RT @CryptoPepes: CryptoPepes just soft launche...,93,2018-10-27 23:02:48
4,4,victordorofeev1,RT @SolarisCoin: Take a peek @ https://t.co/W8...,49,2018-10-27 23:01:47

In [63]:
df.isnull().sum()

Unnamed: 0      0
author          0
description    10
publisher       0
source_url      0
timeStamp       0
title           0
dtype: int64

In [64]:
df.dropna(inplace = True)
df.isnull().sum()

Unnamed: 0     0
author         0
description    0
publisher      0
source_url     0
timeStamp      0
title          0
dtype: int64

In [65]:
def remove_punct(text):
    text_nopunct = "".join([char for char in text if char not in punctuation])
    return(text_nopunct)

df['cleaned_description'] = df['description'].apply(lambda x: remove_punct(x))

df.head()

,Unnamed: 0,author,description,publisher,source_url,timeStamp,title,cleaned_description
0,0,Phillip Molnar,A British real estate company Monday launched ...,Sandiegouniontribune.com,http://www.sandiegouniontribune.com/business/r...,2018-01-09 00:00:00,"Purplebricks, flat fee real estate listers, la...",A British real estate company Monday launched ...
1,1,Ml-implode.com,``In parts of the continent - especially comme...,Ml-implode.com,http://ml-implode.com/staticnews/2018-01-09_Wh...,2018-01-09 00:00:00,Why African millennials can't get enough of Bi...,In parts of the continent especially commerci...
2,2,"Associated Press, By Associated Press","NEW YORK — Kodak, which traces its roots to th...",Bostonherald.com,http://www.bostonherald.com/news/national/2018...,2018-01-09 00:00:00,Kodak surges at it becomes latest 'cryptocurre...,NEW YORK — Kodak which traces its roots to the...
3,3,Ml-implode.com,``JPMorgan Chase CEO Jamie Dimon has walked ba...,Ml-implode.com,http://ml-implode.com/staticnews/2018-01-09_Di...,2018-01-09 00:00:00,"Dimon: ""I regret calling bitcoin a fraud""",JPMorgan Chase CEO Jamie Dimon has walked back...
4,4,Ml-implode.com,"``Staff at the regulatory agency ""expressed co...",Ml-implode.com,http://ml-implode.com/staticnews/2018-01-09_Fu...,2018-01-09 00:00:00,Fund managers say bitcoin ETF proposals withdr...,Staff at the regulatory agency expressed conce...

In [66]:
def tokenize(text):
    tokens = re.split('\W+', text)
    return tokens

df['tokenized_cleaned_description'] = df['cleaned_description'].apply(lambda x: tokenize(x.lower()))
df.head()

,Unnamed: 0,author,description,publisher,source_url,timeStamp,title,cleaned_description,tokenized_cleaned_description
0,0,Phillip Molnar,A British real estate company Monday launched ...,Sandiegouniontribune.com,http://www.sandiegouniontribune.com/business/r...,2018-01-09 00:00:00,"Purplebricks, flat fee real estate listers, la...",A British real estate company Monday launched ...,"[a, british, real, estate, company, monday, la..."
1,1,Ml-implode.com,``In parts of the continent - especially comme...,Ml-implode.com,http://ml-implode.com/staticnews/2018-01-09_Wh...,2018-01-09 00:00:00,Why African millennials can't get enough of Bi...,In parts of the continent especially commerci...,"[in, parts, of, the, continent, especially, co..."
2,2,"Associated Press, By Associated Press","NEW YORK — Kodak, which traces its roots to th...",Bostonherald.com,http://www.bostonherald.com/news/national/2018...,2018-01-09 00:00:00,Kodak surges at it becomes latest 'cryptocurre...,NEW YORK — Kodak which traces its roots to the...,"[new, york, kodak, which, traces, its, roots, ..."
3,3,Ml-implode.com,``JPMorgan Chase CEO Jamie Dimon has walked ba...,Ml-implode.com,http://ml-implode.com/staticnews/2018-01-09_Di...,2018-01-09 00:00:00,"Dimon: ""I regret calling bitcoin a fraud""",JPMorgan Chase CEO Jamie Dimon has walked back...,"[jpmorgan, chase, ceo, jamie, dimon, has, walk..."
4,4,Ml-implode.com,"``Staff at the regulatory agency ""expressed co...",Ml-implode.com,http://ml-implode.com/staticnews/2018-01-09_Fu...,2018-01-09 00:00:00,Fund managers say bitcoin ETF proposals withdr...,Staff at the regulatory agency expressed conce...,"[staff, at, the, regulatory, agency, expressed..."

In [91]:
def remove_stopwords(tokenized_list):
    text = [word for word in tokenized_list if word not in stopwords.words('english')]
    return text

df['removedstop_tokenized_cleaned_description'] = df['tokenized_cleaned_description'].apply(lambda x: remove_stopwords(x))

df.head()

,Unnamed: 0,author,description,publisher,source_url,timeStamp,title,cleaned_description,tokenized_cleaned_description,removedstop_tokenized_cleaned_description
0,0,Phillip Molnar,A British real estate company Monday launched ...,Sandiegouniontribune.com,http://www.sandiegouniontribune.com/business/r...,2018-01-09 00:00:00,"Purplebricks, flat fee real estate listers, la...",A British real estate company Monday launched ...,"[a, british, real, estate, company, monday, la...","[british, real, estate, company, monday, launc..."
1,1,Ml-implode.com,``In parts of the continent - especially comme...,Ml-implode.com,http://ml-implode.com/staticnews/2018-01-09_Wh...,2018-01-09 00:00:00,Why African millennials can't get enough of Bi...,In parts of the continent especially commerci...,"[in, parts, of, the, continent, especially, co...","[parts, continent, especially, commercial, hub..."
2,2,"Associated Press, By Associated Press","NEW YORK — Kodak, which traces its roots to th...",Bostonherald.com,http://www.bostonherald.com/news/national/2018...,2018-01-09 00:00:00,Kodak surges at it becomes latest 'cryptocurre...,NEW YORK — Kodak which traces its roots to the...,"[new, york, kodak, which, traces, its, roots, ...","[new, york, kodak, traces, roots, early, days,..."
3,3,Ml-implode.com,``JPMorgan Chase CEO Jamie Dimon has walked ba...,Ml-implode.com,http://ml-implode.com/staticnews/2018-01-09_Di...,2018-01-09 00:00:00,"Dimon: ""I regret calling bitcoin a fraud""",JPMorgan Chase CEO Jamie Dimon has walked back...,"[jpmorgan, chase, ceo, jamie, dimon, has, walk...","[jpmorgan, chase, ceo, jamie, dimon, walked, b..."
4,4,Ml-implode.com,"``Staff at the regulatory agency ""expressed co...",Ml-implode.com,http://ml-implode.com/staticnews/2018-01-09_Fu...,2018-01-09 00:00:00,Fund managers say bitcoin ETF proposals withdr...,Staff at the regulatory agency expressed conce...,"[staff, at, the, regulatory, agency, expressed...","[staff, regulatory, agency, expressed, concern..."

In [106]:
nltk.download('wordnet')
lemmatizer = nltk.stem.WordNetLemmatizer()
ps = nltk.PorterStemmer()

[nltk_data] Downloading package wordnet to /Users/jiahua/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [107]:
def lemmatizing(tokenized_text):
    text = [lemmatizer.lemmatize(word) for word in tokenized_text]
    return text

df['lemmatized_removedstop_tokenized_cleaned_description'] = df['removedstop_tokenized_cleaned_description'].apply(lambda x: lemmatizing(x))

df.head(5)

,Unnamed: 0,author,description,publisher,source_url,timeStamp,title,cleaned_description,tokenized_cleaned_description,removedstop_tokenized_cleaned_description,lemmatized_removedstop_tokenized_cleaned_description
0,0,Phillip Molnar,A British real estate company Monday launched ...,Sandiegouniontribune.com,http://www.sandiegouniontribune.com/business/r...,2018-01-09 00:00:00,"Purplebricks, flat fee real estate listers, la...",A British real estate company Monday launched ...,"[a, british, real, estate, company, monday, la...","[british, real, estate, company, monday, launc...","[british, real, estate, company, monday, launc..."
1,1,Ml-implode.com,``In parts of the continent - especially comme...,Ml-implode.com,http://ml-implode.com/staticnews/2018-01-09_Wh...,2018-01-09 00:00:00,Why African millennials can't get enough of Bi...,In parts of the continent especially commerci...,"[in, parts, of, the, continent, especially, co...","[parts, continent, especially, commercial, hub...","[part, continent, especially, commercial, hub,..."
2,2,"Associated Press, By Associated Press","NEW YORK — Kodak, which traces its roots to th...",Bostonherald.com,http://www.bostonherald.com/news/national/2018...,2018-01-09 00:00:00,Kodak surges at it becomes latest 'cryptocurre...,NEW YORK — Kodak which traces its roots to the...,"[new, york, kodak, which, traces, its, roots, ...","[new, york, kodak, traces, roots, early, days,...","[new, york, kodak, trace, root, early, day, fi..."
3,3,Ml-implode.com,``JPMorgan Chase CEO Jamie Dimon has walked ba...,Ml-implode.com,http://ml-implode.com/staticnews/2018-01-09_Di...,2018-01-09 00:00:00,"Dimon: ""I regret calling bitcoin a fraud""",JPMorgan Chase CEO Jamie Dimon has walked back...,"[jpmorgan, chase, ceo, jamie, dimon, has, walk...","[jpmorgan, chase, ceo, jamie, dimon, walked, b...","[jpmorgan, chase, ceo, jamie, dimon, walked, b..."
4,4,Ml-implode.com,"``Staff at the regulatory agency ""expressed co...",Ml-implode.com,http://ml-implode.com/staticnews/2018-01-09_Fu...,2018-01-09 00:00:00,Fund managers say bitcoin ETF proposals withdr...,Staff at the regulatory agency expressed conce...,"[staff, at, the, regulatory, agency, expressed...","[staff, regulatory, agency, expressed, concern...","[staff, regulatory, agency, expressed, concern..."

In [113]:
def stemming(tokenized_text):
    text = [ps.stem(word) for word in tokenized_text]
    return text

df['stemmed_removedstop_tokenized_cleaned_description'] = df['removedstop_tokenized_cleaned_description'].apply(lambda x: stemming(x))

df.head()

,Unnamed: 0,author,description,publisher,source_url,timeStamp,title,cleaned_description,tokenized_cleaned_description,removedstop_tokenized_cleaned_description,lemmatized_removedstop_tokenized_cleaned_description,stemmed_removedstop_tokenized_cleaned_description
0,0,Phillip Molnar,A British real estate company Monday launched ...,Sandiegouniontribune.com,http://www.sandiegouniontribune.com/business/r...,2018-01-09 00:00:00,"Purplebricks, flat fee real estate listers, la...",A British real estate company Monday launched ...,"[a, british, real, estate, company, monday, la...","[british, real, estate, company, monday, launc...","[british, real, estate, company, monday, launc...","[british, real, estat, compani, monday, launch..."
1,1,Ml-implode.com,``In parts of the continent - especially comme...,Ml-implode.com,http://ml-implode.com/staticnews/2018-01-09_Wh...,2018-01-09 00:00:00,Why African millennials can't get enough of Bi...,In parts of the continent especially commerci...,"[in, parts, of, the, continent, especially, co...","[parts, continent, especially, commercial, hub...","[part, continent, especially, commercial, hub,...","[part, contin, especi, commerci, hub, like, la..."
2,2,"Associated Press, By Associated Press","NEW YORK — Kodak, which traces its roots to th...",Bostonherald.com,http://www.bostonherald.com/news/national/2018...,2018-01-09 00:00:00,Kodak surges at it becomes latest 'cryptocurre...,NEW YORK — Kodak which traces its roots to the...,"[new, york, kodak, which, traces, its, roots, ...","[new, york, kodak, traces, roots, early, days,...","[new, york, kodak, trace, root, early, day, fi...","[new, york, kodak, trace, root, earli, day, fi..."
3,3,Ml-implode.com,``JPMorgan Chase CEO Jamie Dimon has walked ba...,Ml-implode.com,http://ml-implode.com/staticnews/2018-01-09_Di...,2018-01-09 00:00:00,"Dimon: ""I regret calling bitcoin a fraud""",JPMorgan Chase CEO Jamie Dimon has walked back...,"[jpmorgan, chase, ceo, jamie, dimon, has, walk...","[jpmorgan, chase, ceo, jamie, dimon, walked, b...","[jpmorgan, chase, ceo, jamie, dimon, walked, b...","[jpmorgan, chase, ceo, jami, dimon, walk, back..."
4,4,Ml-implode.com,"``Staff at the regulatory agency ""expressed co...",Ml-implode.com,http://ml-implode.com/staticnews/2018-01-09_Fu...,2018-01-09 00:00:00,Fund managers say bitcoin ETF proposals withdr...,Staff at the regulatory agency expressed conce...,"[staff, at, the, regulatory, agency, expressed...","[staff, regulatory, agency, expressed, concern...","[staff, regulatory, agency, expressed, concern...","[staff, regulatori, agenc, express, concern, r..."